name: 👷‍♀️ Build firmware
on: [push]
jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Set up Git repository
        uses: actions/checkout@v3

      - name: 🔨 Set up toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10.3-2021.07'

      - name: 👷‍♀️ Build firmware
        run: make

      - name: ⬆️ Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: Firmware
          path: main.elf